In [49]:
#viola jones algorithm

import numpy as np
import cv2
import skimage
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# ,0 automatically converts the image into gray image
img = cv2.imread('images.jpg')
recognizer = cv2.face.createEigenFaceRecognizer()
#cv2.imshow('img',img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [2]:
#faces = face_cascade.detectMultiScale(img, 1.3, 5)
faces = face_cascade.detectMultiScale(
        img,
        scaleFactor=1.3,
        minNeighbors=5,
        flags= cv2.CASCADE_SCALE_IMAGE
    )
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    cropped = img[y:y+h, x:x+w]
    

In [3]:
cv2.imshow('img',img)
#cv2.imwrite('img1.jpg',cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: /root/mc-x64-2.7/conda-bld/opencv-3_1482254119970/work/opencv-3.1.0/modules/highgui/src/window.cpp:545: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage


In [47]:
import os
count=-1
# traverse root directory, and list directories as dirs and files as files
data = ""
for root, dirs, files in os.walk("../CNN/lfw/lfw"):
    path = root.split(os.sep)
    #print((len(path) - 1) * '---', os.path.basename(root))
    dir1 = os.path.basename(root)
    count=count+1
    for file in files:
        if file.endswith(".jpg"):
            
            list1 = LBP("../CNN/lfw/lfw/"+dir1+"/"+file)
            data += ",".join(str(x) for x in list1) +","+ str(count) + " \n"
with open("LFW.csv", "a") as f:
    f.write(data)

In [54]:
import cv2
import os
from skimage.feature import local_binary_pattern
from scipy.stats import itemfreq 
from sklearn.preprocessing import normalize 
import csv
from PIL import Image
import matplotlib.pyplot as plt

def LBP(imgPath):
    
    img = cv2.imread(imgPath, 0)
    faces = face_cascade.detectMultiScale(
        img,
        scaleFactor=1.3,
        minNeighbors=5,
        flags= cv2.CASCADE_SCALE_IMAGE
    )
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        im_gray = img[y:y+h, x:x+w]
    
    #print(im_gray.shape)
    
#     im_gray = cv2.cvtColor( im_gray, cv2.COLOR_BGR2GRAY )
#     im_gray = cv2.
    radius = 1
    no_points = 8 * radius
    lbp = local_binary_pattern(im_gray, no_points, radius, method='uniform') 
    lbp_img = Image.fromarray(lbp)
    #plt.subplot(121),plt.imshow(lbp_img)
    #x = itemfreq(lbp.ravel())
    #ans=sorted(set(lbp.ravel()))
    #plt.subplot(122),plt.hist(lbp.ravel(),normed=True,bins=9)
    #plt.show()

    n,bins,patches = plt.hist(lbp.ravel(),normed=True,bins=58)
    return n


(160, 160)
[ 0.19182292  0.          0.          0.          0.          0.
  0.33631944  0.          0.          0.          0.          0.          0.2628125
  0.          0.          0.          0.          0.          0.
  0.76930556  0.          0.          0.          0.          0.
  1.60607639  0.          0.          0.          0.          0.          0.
  1.24886285  0.          0.          0.          0.          0.
  0.46143229  0.          0.          0.          0.          0.          0.
  0.40957465  0.          0.          0.          0.          0.
  0.62480903  0.          0.          0.          0.          0.
  0.53342882]


In [87]:
import os
import dateutil
import pandas
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import numpy
from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn import cross_validation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
dirPath = os.getcwd()
dataSet1 = pandas.read_csv(str(dirPath)+"/Yale DWT_3_edge.csv")
Ydata = dataSet1.ix[0:,len(dataSet1.columns)-1]
dataSet1.drop(dataSet1.columns[[len(dataSet1.columns)-1]], axis=1, inplace=True) 

Xdata = dataSet1
X = numpy.array(Xdata)

Y = numpy.array(Ydata)
validation_size = 0.1
seed = 5
X_train, X_validation, Y_train, Y_validation = cross_validation.train_test_split(X, Y, test_size=validation_size, random_state=seed)
#svm1 = SVC()
svm1 = KNeighborsClassifier()
#svm1 = LinearDiscriminantAnalysis()

svm1.fit(X_train, Y_train)
predictions = svm1.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))


0.8125
[[1 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 1]]
             precision    recall  f1-score   support

          1       0.33      1.00      0.50         1
          3       1.00      0.67      0.80         3
          4       1.00      1.00      1.00         1
          6       1.00      1.00      1.00         2
          7       1.00      0.50      0.67         2
          8       1.00      1.00      1.00         1
          9       0.50      1.00      0.67         1
         13       1.00      0.50      0.67         2
         14       1.00      1.00      1.00         2
         15       1.00      1.00      1.00         1

avg / total       0.93      0.81      0.83        16



In [ ]:
def w2d(imArray, mode='db1', level=3):
    
    #convert to float
    imArray =  np.float32(imArray)   
    imArray /= 255;
    # compute coefficients 
    coeffs=pywt.wavedec2(imArray, mode, level=level)
     
    return coeffs
    